backend:
  name: git-gateway
  branch: master

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

collections:
  # EN
  - name: 'blogEn'
    label: 'Blog (English)'
    filter: { field: language, value: en }
    folder: 'src/pages/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    identifier_field: slug
    extension: 'en.md'
    format: frontmatter
    editor:
      preview: true
    fields:
      - { label: 'Language', name: 'language', widget: hidden, default: en }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string', pattern: [ '^[a-z0-9]+(?:-[a-z0-9]+)*$','A slug can have no spaces or special characters' ] }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string', default: 'Burhan Savcı' }
      - { label: 'Tag',
          name: 'tag',
          widget: 'select',
          options:
            [
                'Javascript',
                'ReactJS',
                'GatsbyJS',
                'Netlify',
                '.NET',
                '.NET Core',
            ], }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  # TR
  - name: 'blogTr'
    label: 'Blog (Turkish)'
    filter: { field: language, value: tr }
    folder: 'src/pages/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    identifier_field: slug
    extension: 'tr.md'
    format: frontmatter
    editor:
      preview: true
    fields:
      - { label: 'Language', name: 'language', widget: hidden, default: tr }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string', pattern: [ '^[a-z0-9]+(?:-[a-z0-9]+)*$','A slug can have no spaces or special characters' ] }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string', default: 'Burhan Savcı' }
      - { label: 'Tag',
          name: 'tag',
          widget: 'select',
          options:
            [
                'Javascript',
                'ReactJS',
                'GatsbyJS',
                'Netlify',
                '.NET',
                '.NET Core',
            ], }
      - { label: 'Body', name: 'body', widget: 'markdown' }