backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/posts'
    media_folder: 'static/images'
    public_folder: '/images'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Tag', name: 'tag', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }